'use client';

import React, { createContext, useContext, useState } from 'react';

export const translations = {
  en: {
    nav: {
      home: 'Home',
      menu: 'Menu',
      reservation: 'Reservation',
      about: 'About',
      admin: 'Admin',
      reserveTable: 'Book a Table',
    },
    hero: {
      tag: 'Luxury Dining & Royal Hospitality',
      welcome: 'Welcome to Diamond C',
      tagline: 'Bienvenue chez Diamond C',
      subtitle: 'Experience authentic Cameroonian delicacies and exquisite fine dining in an elegant, modern gold-kissed setting.',
      exploreMenu: 'Explore Our Menu',
      reserveTable: 'Reserve a Table',
      signatureNotice: 'Douala, Cameroon • Mon - Sun: 8:00 AM - 11:00 PM',
    },
    story: {
      tag: 'The Diamond C Story',
      title: 'A Culinary Journey of Prestige',
      subtitle: 'Where authentic Cameroonian heritage meets royal luxury and modern mastery.',
      p1: 'Located in the heart of Douala, Diamond C brings together traditional heritage recipes and modern culinary artistry. Founded on a deep passion for authentic Cameroonian hospitality, we offer a warm, high-end sanctuary where every meal is treated as an extraordinary celebration.',
      p2: 'From the royal golden soup of Achu and rich wild-leaf Eru to charcoal-braised tilapia fish and savory Ndolé crowned with colossal tiger prawns, our dishes are crafted with hand-selected indigenous spices, fresh ingredients, and five-star culinary finesse.',
      p3: 'Whether you join us for our daily specials, conduct an executive business lunch in our private salon, or celebrate an evening in our VIP Lounge, our dedicated team guarantees an unforgettable dining journey.',
      button: 'View Daily Menu',
      loungeTitle: 'Exclusive VIP Wine & Dining Lounge',
      loungeDesc: 'Reserved for private summits, anniversaries, and distinguished diners seeking privacy and bespoke gastronomic service.',
    },
    menu: {
      title: 'Daily Curated Menu',
      subtitle: 'Organized strictly by days of the week. Every day at Diamond C unveils freshly prepared authentic Cameroonian specialties.',
      allDays: 'All Days',
      selectDayHint: 'Select a day to view daily meals',
      today: 'Today',
      orderNow: 'Order Now',
      inStock: 'In Stock',
      soldOut: 'Sold Out',
      filterAll: 'All Categories',
      filterCameroonian: 'Cameroonian Specials (90%)',
      filterContinental: 'Chef Creations',
      filterBeverages: 'Royal Drinks & Cellar',
      searchPlaceholder: 'Search dishes, ingredients...',
      scrollHint: 'Scroll horizontally to explore daily dishes',
      servedOn: 'Served on:',
      emptyDishes: 'No dishes scheduled for this day yet. Check back soon or visit our Admin portal.',
    },
    reservation: {
      title: 'Table Reservation',
      subtitle: 'Book your dining experience at Diamond C. Complete the form below to confirm instantly via our VIP WhatsApp concierge.',
      fullName: 'Full Name',
      namePlaceholder: 'e.g. Jean-Paul Mbarga',
      phoneNumber: 'WhatsApp / Phone Number',
      phonePlaceholder: '+237 6XX XXX XXX',
      guests: 'Number of Persons / Guests',
      guestsPlaceholder: 'Select number of guests',
      guest1: '1 Person (Solo Dining)',
      guest2: '2 Persons (Romantic / Couple)',
      guest3: '3 - 4 Persons (Family & Friends)',
      guestVIP: '5 - 8 Persons (VIP Table)',
      guestEvent: '9+ Persons (Private Dining / Banquet)',
      tablePreference: 'Table Preference',
      tableIndoor: 'Indoor Main Dining Hall',
      tableVIP: 'Royal VIP Lounge',
      tableTerrace: 'Outdoor Terrace & Courtyard',
      dateTime: 'Date & Time',
      notes: 'Special Requests / Occasion (Optional)',
      notesPlaceholder: 'Birthday celebration, champagne on ice, anniversary, dietary preferences...',
      submitBtn: 'Confirm via WhatsApp',
      instantNotice: 'Instant Confirmation: Your details will open formatted in WhatsApp to contact our concierge immediately.',
      directCallTitle: 'Need immediate assistance?',
      directCallDesc: 'Our concierge desk is available 8:00 AM – 11:00 PM.',
      callNumber: '+237 600 000 000',
    },
    about: {
      tag: 'About Diamond C',
      title: 'Redefining African Gastronomy in Douala',
      subtitle: 'A sanctuary of refined flavor, warm Cameroonian heritage, and royal service.',
      storyHeading: 'Our Heritage & Philosophy',
      storyText: 'At Diamond C, we believe dining should captivate every sense. Our culinary team draws deep inspiration from Cameroon’s diverse culinary map—from the Western and North Western highlands known for Achu and Kati Kati, to the coastal shores of Douala and Limbe celebrating Ndolé and seasoned charcoal-braised fresh sea catch.',
      standardsHeading: 'Uncompromising Culinary Standards',
      standardsText: 'We source only fresh organic herbs, Penja pepper, pure palm oil, and premium livestock. Each dish is slow-cooked to ancestral standards, then plated with the sophistication of international haute cuisine.',
      experienceHeading: 'The Diamond C Ambiance',
      experienceText: 'Subtle golden accents, dark polished woods, warm amber lighting, and curated acoustic jazz create an atmosphere designed for relaxation, business summits, and joyous gatherings.',
      hoursHeading: 'Opening Hours',
      hoursDesc: 'Monday through Sunday: 8:00 AM – 11:00 PM',
      locationHeading: 'Location Address',
      locationDesc: 'Douala, Littoral Region, Cameroon',
    },
    preview: {
      title: 'Explore Menu Preview',
      subtitle: 'A glimpse into our signature dishes and specialty drinks prepared fresh daily.',
      viewFullMenu: 'View Full Weekly Menu',
    },
    footer: {
      headline: 'Visit Diamond C',
      tagline: 'Authentic Cameroonian Culinary Prestige',
      aboutText: 'Diamond C is Douala’s destination for luxury dining, celebrating the authentic flavors of Cameroon alongside exquisite refreshments.',
      quickLinks: 'Navigation',
      hoursTitle: 'Opening Hours',
      hoursSchedule: 'Mon – Sun: 8:00 AM – 11:00 PM',
      kitchenNotice: 'Kitchen service until 10:30 PM',
      contactTitle: 'Essential Info',
      location: 'Location: Douala, Cameroon',
      phone: 'Phone / WhatsApp: +237 600 000 000',
      website: 'Website: diamondc-restaurant.com',
      rights: 'All Rights Reserved. Diamond C Restaurant.',
    },
    admin: {
      title: 'Diamond C Admin Portal',
      subtitle: 'Manage daily food items, prices, active days, and stock status.',
      loginTitle: 'Manager Authentication',
      loginSubtitle: 'Enter administrator credentials to access the menu management panel.',
      username: 'Username',
      password: 'Password',
      signIn: 'Sign In to Dashboard',
      invalidCredentials: 'Invalid username or password. Please try again.',
      dashboardTitle: 'Menu Management Panel',
      addDish: 'Add Food Item',
      resetDefaults: 'Reset to Sample Cameroonian Dishes',
      resetConfirm: 'Are you sure you want to reset all dishes to default Cameroonian specialties?',
      totalDishes: 'Total Dishes',
      activeToday: 'Active Today',
      inStock: 'In Stock',
      soldOut: 'Sold Out',
      searchPlaceholder: 'Search dishes...',
      filterAll: 'All Days',
      tableImage: 'Image',
      tableName: 'Dish Name',
      tableCategory: 'Category',
      tablePrice: 'Price',
      tableDays: 'Assigned Days',
      tableStock: 'Availability',
      tableActions: 'Actions',
      edit: 'Edit',
      delete: 'Delete',
      confirmDelete: 'Are you sure you want to delete this dish?',
      modalAddTitle: 'Add New Food Item',
      modalEditTitle: 'Edit Food Item',
      fieldDishNameEn: 'Dish Name (English)',
      fieldDishNameFr: 'Dish Name (French)',
      fieldPrice: 'Price (e.g. 7,500 FCFA)',
      fieldCategory: 'Category',
      fieldImage: 'Image URL or Preset',
      fieldDays: 'Assigned Days of the Week',
      fieldDescEn: 'Description (English)',
      fieldDescFr: 'Description (French)',
      fieldInStock: 'Item is In Stock',
      save: 'Save Dish',
      cancel: 'Cancel',
      logout: 'Log Out',
      viewSite: 'View Live Website',
      webStorageNotice: 'All changes are stored locally in your browser (Web Storage) and update the live website immediately.',
    }
  },
  fr: {
    nav: {
      home: 'Accueil',
      menu: 'Menu',
      reservation: 'Réservation',
      about: 'À Propos',
      admin: 'Admin',
      reserveTable: 'Réserver une table',
    },
    hero: {
      tag: 'Haute Gastronomie & Accueil Royal',
      welcome: 'Bienvenue chez Diamond C',
      tagline: 'Bienvenue chez Diamond C',
      subtitle: 'Dégustez les mets les plus raffinés du terroir camerounais et une cuisine d’exception dans un cadre royal, moderne et doré.',
      exploreMenu: 'Découvrir le Menu',
      reserveTable: 'Réserver une Table',
      signatureNotice: 'Douala, Cameroun • Lun - Dim : 08h00 - 23h00',
    },
    story: {
      tag: "L'Histoire de Diamond C",
      title: 'Une Odyssée Culinaire de Prestige',
      subtitle: 'Quand la tradition culinaire camerounaise rencontre le luxe et le raffinement.',
      p1: "Situé au cœur de Douala, Diamond C rassemble les trésors gastronomiques ancestraux du Cameroun et la haute cuisine moderne. Fondé sur un attachement profond à l'hospitalité camerounaise, notre établissement vous accueille dans un cadre intime et luxueux.",
      p2: "Du noble Achu à la sauce jaune dorée et l'authentique Eru aux feuilles sauvages, en passant par notre poisson tilapia braisé au feu de bois et le savoureux Ndolé aux gambas royales tigrées, chaque mets est concocté avec des épices sélectionnées à la main et une exigence gastronomique cinq étoiles.",
      p3: "Que vous veniez pour nos menus du jour, un déjeuner d'affaires dans notre salon privé ou une soirée intime dans notre salon VIP, notre équipe se voue à faire de votre venue un moment mémorable.",
      button: 'Découvrir le Menu Quotidien',
      loungeTitle: 'Lounge VIP Exclusif Vins & Gastronomie',
      loungeDesc: 'Réservé aux rencontres diplomatiques, réceptions privées et amateurs de gastronomie recherchant discrétion et service sur-mesure.',
    },
    menu: {
      title: 'Menu Quotidien Raffiné',
      subtitle: 'Organisé jour par jour du lundi au dimanche. Chaque journée chez Diamond C révèle des spécialités camerounaises fraîches.',
      allDays: 'Tous les jours',
      selectDayHint: 'Sélectionnez un jour pour voir les plats du jour',
      today: "Aujourd'hui",
      orderNow: 'Commander',
      inStock: 'En Stock',
      soldOut: 'Épuisé',
      filterAll: 'Toutes les catégories',
      filterCameroonian: 'Spécialités Camerounaises (90%)',
      filterContinental: 'Créations du Chef',
      filterBeverages: 'Boissons Royales & Cave',
      searchPlaceholder: 'Rechercher un plat, ingrédient...',
      scrollHint: 'Faites défiler horizontalement pour découvrir les plats',
      servedOn: 'Servi le :',
      emptyDishes: 'Aucun plat programmé pour ce jour actuellement. Consultez notre portail d’administration.',
    },
    reservation: {
      title: 'Réservation de Table',
      subtitle: 'Réservez votre table chez Diamond C. Remplissez le formulaire ci-dessous pour confirmer immédiatement via notre conciergerie WhatsApp.',
      fullName: 'Nom Complet',
      namePlaceholder: 'ex. Jean-Paul Mbarga',
      phoneNumber: 'Numéro WhatsApp / Téléphone',
      phonePlaceholder: '+237 6XX XXX XXX',
      guests: 'Nombre de Personnes',
      guestsPlaceholder: 'Sélectionnez le nombre de convives',
      guest1: '1 Personne (En solo)',
      guest2: '2 Personnes (Romantique / Couple)',
      guest3: '3 - 4 Personnes (Famille / Amis)',
      guestVIP: '5 - 8 Personnes (Table VIP)',
      guestEvent: '9+ Personnes (Banquet / Salon Privé)',
      tablePreference: 'Préférence de Table',
      tableIndoor: 'Salle Principale Climatisée',
      tableVIP: 'Salon Royal VIP',
      tableTerrace: 'Terrasse Extérieure & Jardin',
      dateTime: 'Date & Heure',
      notes: 'Demandes Particulières / Occasion (Optionnel)',
      notesPlaceholder: 'Anniversaire, champagne au frais, fleurs, restrictions alimentaires...',
      submitBtn: 'Confirmer sur WhatsApp',
      instantNotice: 'Confirmation instantanée : vos coordonnées s’ouvriront pré-remplies dans WhatsApp pour contacter notre conciergerie.',
      directCallTitle: 'Besoin d’assistance immédiate ?',
      directCallDesc: 'Notre conciergerie est à votre service de 08h00 à 23h00.',
      callNumber: '+237 600 000 000',
    },
    about: {
      tag: 'À Propos de Diamond C',
      title: "Sublimer l'Art Culinaire Africain à Douala",
      subtitle: 'Un sanctuaire de saveurs raffinées, de patrimoine camerounais et de service royal.',
      storyHeading: 'Notre Histoire & Philosophie',
      storyText: "Chez Diamond C, nous concevons la gastronomie comme un art qui éveille tous les sens. Nos chefs s'inspirent des terroirs du Cameroun : des hauts plateaux de l'Ouest et du Nord-Ouest réputés pour l'Achu et le Kati Kati, jusqu'aux côtes de Douala et Limbe célébrant le Ndolé et les poissons braisés à la braise parfumée.",
      standardsHeading: 'Exigence & Authenticité',
      standardsText: "Nous sélectionnons rigoureusement poivre de Penja, épices sauvages, huile de palme vierge et viandes fermières. Chaque mets est cuisiné selon les préceptes traditionnels puis dressé avec la précision de la haute gastronomie contemporaine.",
      experienceHeading: "L'Ambiance Diamond C",
      experienceText: "Éclats d'or chaleureux, boiseries foncées polies, lumières tamisées ambrées et mélodies de jazz feutré composent un univers propice à la détente, aux dîners d'affaires et aux célébrations inoubliables.",
      hoursHeading: 'Horaires de Service',
      hoursDesc: 'Du Lundi au Dimanche : 08h00 – 23h00',
      locationHeading: 'Adresse & Localisation',
      locationDesc: 'Douala, Région du Littoral, Cameroun',
    },
    preview: {
      title: 'Aperçu du Menu',
      subtitle: 'Un avant-goût de nos mets signatures et boissons de prestige préparés chaque jour.',
      viewFullMenu: 'Voir la Carte Complète',
    },
    footer: {
      headline: 'Rendez-vous chez Diamond C',
      tagline: 'Prestige Culinaire Camerounais',
      aboutText: 'Diamond C est l’adresse par excellence à Douala pour la haute gastronomie, magnifiant les recettes du terroir camerounais.',
      quickLinks: 'Navigation',
      hoursTitle: 'Horaires d’Ouverture',
      hoursSchedule: 'Lun – Dim : 08h00 – 23h00',
      kitchenNotice: 'Dernière commande en cuisine à 22h30',
      contactTitle: 'Informations Pratiques',
      location: 'Lieu : Douala, Cameroun',
      phone: 'Téléphone / WhatsApp : +237 600 000 000',
      website: 'Site web : diamondc-restaurant.com',
      rights: 'Tous droits réservés. Restaurant Diamond C.',
    },
    admin: {
      title: 'Portail Administrateur Diamond C',
      subtitle: 'Gérez les plats du jour, les prix, les jours d’attribution et la disponibilité.',
      loginTitle: 'Authentification Gestionnaire',
      loginSubtitle: 'Saisissez vos identifiants administrateur pour accéder à la gestion du menu.',
      username: 'Nom d’utilisateur',
      password: 'Mot de passe',
      signIn: 'Se connecter au tableau de bord',
      invalidCredentials: 'Identifiant ou mot de passe incorrect. Veuillez réessayer.',
      dashboardTitle: 'Panneau de Gestion du Menu',
      addDish: 'Ajouter un Plat',
      resetDefaults: 'Restaurer les Spécialités Camerounaises',
      resetConfirm: 'Voulez-vous vraiment réinitialiser les plats par défaut ?',
      totalDishes: 'Total Plats',
      activeToday: "Actifs Aujourd'hui",
      inStock: 'En Stock',
      soldOut: 'Épuisé',
      searchPlaceholder: 'Filtrer les plats...',
      filterAll: 'Tous les jours',
      tableImage: 'Photo',
      tableName: 'Nom du Plat',
      tableCategory: 'Catégorie',
      tablePrice: 'Prix',
      tableDays: 'Jours Assignés',
      tableStock: 'Disponibilité',
      tableActions: 'Actions',
      edit: 'Modifier',
      delete: 'Supprimer',
      confirmDelete: 'Êtes-vous sûr de vouloir supprimer ce plat ?',
      modalAddTitle: 'Ajouter un Nouveau Plat',
      modalEditTitle: 'Modifier le Plat',
      fieldDishNameEn: 'Nom du Plat (Anglais)',
      fieldDishNameFr: 'Nom du Plat (Français)',
      fieldPrice: 'Prix (ex. 7 500 FCFA)',
      fieldCategory: 'Catégorie',
      fieldImage: 'URL de l’image ou Préréglage',
      fieldDays: 'Jours d’Affichage de la Semaine',
      fieldDescEn: 'Description (Anglais)',
      fieldDescFr: 'Description (Français)',
      fieldInStock: 'Le plat est disponible (En Stock)',
      save: 'Enregistrer le Plat',
      cancel: 'Annuler',
      logout: 'Déconnexion',
      viewSite: 'Voir le Site en Direct',
      webStorageNotice: 'Toutes les modifications sont enregistrées localement dans votre navigateur (Web Storage) et mettent à jour le site instantanément.',
    }
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('diamond_c_lang');
      if (saved === 'fr' || saved === 'en') return saved;
    }
    return 'en';
  });

  const switchLanguage = (newLang) => {
    setLang(newLang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('diamond_c_lang', newLang);
    }
  };

  const t = translations[lang] || translations.en;

  return (
    <LanguageContext.Provider value={{ lang, setLang: switchLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
